version: '3.8'

services:
  app:
    image: arijnabli10/laravel:5
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: restaurant
      DB_USERNAME: root
      DB_PASSWORD: 
      APP_URL: http://localhost/


  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ValidationLaravel22
      MYSQL_ROOT_PASSWORD: 
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
      - "7000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - db
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge
