
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: arijnabli10/laravel:38
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: 127.0.0.1
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ValidationLaravel22
      MYSQL_ROOT_PASSWORD: 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

