version: '3.8'

services:
  # Application Service
  app:
    container_name: blog
    image: arijnabli10/laravel:38  # Utilisation de l'image spécifiée
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    depends_on:
      - db

  # Database Service
  db:
    image: mysql:5.7
    container_name: mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ValidationLaravel22  # Nom de votre base de données
      MYSQL_ROOT_PASSWORD: ""  # Mot de passe root
      MYSQL_PASSWORD: ""  # Mot de passe pour l'utilisateur
      MYSQL_USER: root  # Utilisateur root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d  # Scripts d'initialisation de la base de données
    networks:
      - travellist

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/default.conf  # Utilisation du fichier default.conf
    depends_on:
      - app
      - db

networks:
  travellist:
    driver: bridge